/**
 * インシデント対応Bot - Lambda Handler
 * 
 * 処理フロー:
 * 1. SNS からアラーム情報を受信
 * 2. CloudWatch Logs からエラーログを取得
 * 3. Claude API で原因を分析
 * 4. SES でメール通知
 */

import {
  SecretsManagerClient,
  GetSecretValueCommand,
} from "@aws-sdk/client-secrets-manager";
import {
  CloudWatchLogsClient,
  FilterLogEventsCommand,
} from "@aws-sdk/client-cloudwatch-logs";
import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";

const secretsClient = new SecretsManagerClient({});
const logsClient = new CloudWatchLogsClient({});
const sesClient = new SESClient({});

const CLAUDE_API_KEY_SECRET_NAME = process.env.CLAUDE_API_KEY_SECRET_NAME;
const NOTIFICATION_EMAIL = process.env.NOTIFICATION_EMAIL;

/**
 * Secrets Manager からシークレットを取得
 */
async function getSecret(secretName, key) {
  const command = new GetSecretValueCommand({ SecretId: secretName });
  const response = await secretsClient.send(command);
  const secret = JSON.parse(response.SecretString);
  return secret[key];
}

/**
 * CloudWatch Logs からエラーログを取得
 */
async function getErrorLogs(logGroupName, startTime, endTime) {
  console.log(`Fetching logs from ${logGroupName}...`);
  
  const command = new FilterLogEventsCommand({
    logGroupName: logGroupName,
    startTime: startTime,
    endTime: endTime,
    filterPattern: "?ERROR ?Error ?error ?Exception ?exception ?FATAL",
    limit: 50,
  });

  try {
    const response = await logsClient.send(command);
    return response.events || [];
  } catch (error) {
    console.error(`Error fetching logs: ${error.message}`);
    return [];
  }
}

/**
 * Claude API で原因を分析
 */
async function analyzeWithClaude(alarmInfo, logs) {
  const apiKey = await getSecret(CLAUDE_API_KEY_SECRET_NAME, "api_key");

  const logsText = logs.length > 0
    ? logs.map(e => `[${new Date(e.timestamp).toISOString()}] ${e.message}`).join("\n")
    : "No error logs found in the specified time range.";

  const prompt = `あなたはSREエンジニアです。以下のCloudWatchアラームとエラーログを分析し、原因と対応策を日本語で簡潔にまとめてください。

## アラーム情報
- アラーム名: ${alarmInfo.alarmName}
- 状態: ${alarmInfo.newState}
- 理由: ${alarmInfo.reason}
- 発生時刻: ${alarmInfo.timestamp}

## エラーログ
${logsText}

## 出力形式
### 原因の推定
（1-2文で簡潔に）

### 影響範囲
（サービスへの影響を簡潔に）

### 推奨対応
1. （最優先の対応）
2. （次の対応）
3. （根本対策）

### 補足
（必要に応じて追加情報）`;

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-20250514",
      max_tokens: 1024,
      messages: [{ role: "user", content: prompt }],
    }),
  });

  if (!response.ok) {
    throw new Error(`Claude API error: ${response.status}`);
  }

  const data = await response.json();
  return data.content[0].text;
}

/**
 * SES でメール通知
 */
async function sendEmailNotification(alarmInfo, analysis) {
  if (!NOTIFICATION_EMAIL) {
    console.log("NOTIFICATION_EMAIL not set, skipping email");
    return false;
  }

  const subject = `[ALERT] ${alarmInfo.alarmName} - ${alarmInfo.newState}`;

  const htmlBody = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #dc2626; border-bottom: 2px solid #dc2626; padding-bottom: 10px; }
    h2, h3 { color: #991b1b; }
    .alert-info { background: #fef2f2; padding: 15px; border-radius: 8px; border-left: 4px solid #dc2626; margin-bottom: 20px; }
    .analysis { background: #f8fafc; padding: 20px; border-radius: 8px; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 12px; }
  </style>
</head>
<body>
  <h1>Incident Alert</h1>
  <div class="alert-info">
    <p><strong>Alarm:</strong> ${alarmInfo.alarmName}</p>
    <p><strong>State:</strong> ${alarmInfo.newState}</p>
    <p><strong>Time:</strong> ${alarmInfo.timestamp}</p>
    <p><strong>Reason:</strong> ${alarmInfo.reason}</p>
  </div>
  <h2>AI Analysis</h2>
  <div class="analysis">
    ${analysis.replace(/\n/g, "<br>").replace(/###/g, "<h3>").replace(/##/g, "<h2>")}
  </div>
  <div class="footer">
    <p>This alert was generated by DevOps AI Cockpit - Incident Analyzer</p>
  </div>
</body>
</html>`;

  const command = new SendEmailCommand({
    Source: NOTIFICATION_EMAIL,
    Destination: { ToAddresses: [NOTIFICATION_EMAIL] },
    Message: {
      Subject: { Charset: "UTF-8", Data: subject },
      Body: {
        Html: { Charset: "UTF-8", Data: htmlBody },
        Text: { Charset: "UTF-8", Data: `${subject}\n\n${analysis}` },
      },
    },
  });

  await sesClient.send(command);
  console.log("Email notification sent successfully");
  return true;
}

/**
 * SNS メッセージからアラーム情報を抽出
 */
function parseAlarmFromSNS(event) {
  const snsRecord = event.Records[0].Sns;
  const message = JSON.parse(snsRecord.Message);

  return {
    alarmName: message.AlarmName,
    alarmDescription: message.AlarmDescription || "",
    newState: message.NewStateValue,
    oldState: message.OldStateValue,
    reason: message.NewStateReason,
    timestamp: snsRecord.Timestamp,
    namespace: message.Trigger?.Namespace || "AWS/Lambda",
    metricName: message.Trigger?.MetricName || "Errors",
    dimensions: message.Trigger?.Dimensions || [],
  };
}

/**
 * Lambda ハンドラー
 */
export const handler = async (event) => {
  console.log("=== Incident Analyzer Started ===");
  console.log("Event:", JSON.stringify(event, null, 2));

  try {
    const alarmInfo = parseAlarmFromSNS(event);
    console.log("Alarm Info:", JSON.stringify(alarmInfo, null, 2));

    // ALARM 状態の場合のみ分析
    if (alarmInfo.newState !== "ALARM") {
      console.log(`State is ${alarmInfo.newState}, skipping analysis`);
      return {
        statusCode: 200,
        body: JSON.stringify({ message: "Not an ALARM state, skipped" }),
      };
    }

    // Lambda 関数名を取得（dimensions から）
    const functionDimension = alarmInfo.dimensions.find(
      (d) => d.name === "FunctionName"
    );
    const functionName = functionDimension?.value || "unknown";
    const logGroupName = `/aws/lambda/${functionName}`;

    // 過去15分のログを取得
    const endTime = Date.now();
    const startTime = endTime - 15 * 60 * 1000;

    const logs = await getErrorLogs(logGroupName, startTime, endTime);
    console.log(`Found ${logs.length} error log events`);

    // Claude で分析
    console.log("Analyzing with Claude...");
    const analysis = await analyzeWithClaude(alarmInfo, logs);
    console.log("Analysis complete");
    console.log("=== Claude Analysis Result ===");
    console.log(analysis);
    console.log("=== End of Analysis ===");

    // メール送信
    const emailSent = await sendEmailNotification(alarmInfo, analysis);

    return {
      statusCode: 200,
      body: JSON.stringify({
        alarmName: alarmInfo.alarmName,
        state: alarmInfo.newState,
        logsAnalyzed: logs.length,
        emailSent: emailSent,
      }),
    };
  } catch (error) {
    console.error("Error:", error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error.message }),
    };
  }
};