AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ShopX Product Catalog API

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    Environment:
      Variables:
        PRODUCTS_TABLE: !Ref ProductsTable
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  # 商品一覧取得
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/getProducts/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProducts:
          Type: Api
          Properties:
            Path: /products
            Method: GET

  # 商品詳細取得
  GetProductByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/getProductById/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProductById:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: GET

  # カテゴリ一覧取得
  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/getCategories/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetCategories:
          Type: Api
          Properties:
            Path: /categories
            Method: GET

  # DynamoDB テーブル
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-products"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ProductsTableName:
    Description: DynamoDB table name
    Value: !Ref ProductsTable