AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ShopX Product Catalog API

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    Environment:
      Variables:
        PRODUCTS_TABLE: !Ref ProductsTable

Resources:
  # ==========================================
  # API Gateway（Cognito Authorizer 付き）
  # ==========================================

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  # ==========================================
  # 商品 API（認証不要）
  # ==========================================

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/getProducts/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /products
            Method: GET

  GetProductByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/getProductById/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProductById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /products/{id}
            Method: GET

  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/getCategories/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetCategories:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /categories
            Method: GET

  # ==========================================
  # カート API（認証必須）
  # ==========================================

  GetCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/getCart/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetCart:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /cart
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/updateCart/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        UpdateCart:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /cart
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  # ==========================================
  # DynamoDB テーブル
  # ==========================================

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-products"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # ==========================================
  # Cognito 認証
  # ==========================================

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-users"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-web-client"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ProductsTableName:
    Description: DynamoDB table name
    Value: !Ref ProductsTable
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient